spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
      path: /db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
server:
  port: 9090


env: local




#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:10001/auth/realms/master
